# Generated by Django 4.1.7 on 2023-02-25 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_backend', '0004_alter_note_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, null='Null'),
        ),
    ]
