# Generated by Django 4.1.7 on 2023-02-25 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_backend', '0006_alter_note_content_alter_note_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='content',
            field=models.TextField(blank=True, null='Null'),
        ),
        migrations.AlterField(
            model_name='note',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
